ecommerceexample/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
]

shop/urls.py
from django.urls import path

from shop import views

app_name = 'shop'
urlpatterns = [
    path(
        'products/',
        views.ProductListView.as_view(),
        name='product-list',
    ),
    path(
        'products/<slug>/',
        views.ProductDetailView.as_view(),
        name='product-detail',
    ),
    path(
        'cart/',
        views.CartView.as_view(),
        name='cart',
    ),
    path(
        'products/<slug>/add-to-cart/',
        views.add_to_cart,
        name='add-to-cart',
    ),
    path(
        'products/<slug>/remove-from-cart/',
        views.remove_from_cart,
        name='remove-from-cart',
    ),
    path(
        'products/cart/empty/',
        views.empty_cart,
        name='empty-cart',
    ),
]

shop/models.py
from django.db import models
from django.shortcuts import reverse


class ProductCategory(models.Model):
    name = models.CharField()
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/products/?category={self.slug}'


class Product(models.Model):
    categories = models.ManyToManyField(ProductCategory)
    name = models.CharField()
    slug = models.SlugField()
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product-detail', kwargs={'slug': self.slug})

    def get_image_path(self):
        return f'shop/images/products/{self.slug}.jpg'

shop/views.py
from decimal import Decimal

from django.contrib.postgres.aggregates import ArrayAgg
from django.contrib.postgres.search import (
    SearchQuery,
    SearchRank,
    SearchVector,
)
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View, generic
from django.views.generic.base import ContextMixin

from shop.models import Product, ProductCategory


class ProductListView(generic.ListView):
    model = Product
    paginate_by = 12

    def get_queryset(self):
        if 'search' in self.request.GET and self.request.GET['search'] != '':
            vector = (
                SearchVector('name', weight='A')
                + SearchVector('category_names', weight='A')
                + SearchVector('description', weight='D')
            )
            query = SearchQuery(self.request.GET['search'])
            products = Product.objects.annotate(
                category_names=ArrayAgg('categories__name', distinct=True),
                rank=SearchRank(vector, query),
            ).filter(rank__gte=0.1).order_by('-rank')
        else:
            products = Product.objects.all()
        if 'category' in self.request.GET:
            products = products.filter(
                categories__slug=self.request.GET['category'],
            )
        return products

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['product_count'] = Product.objects.count()
        data['categories'] = ProductCategory.objects.all().order_by('name')
        data['category_slug'] = self.request.GET.get('category')
        return data


class ProductDetailView(generic.DetailView):
    model = Product


class CartView(generic.TemplateView):
    template_name = 'shop/cart.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        cart = self.request.session.get('cart', {})
        subtotal = Decimal('0.00')
        for product in Product.objects.filter(slug__in=cart.keys()):
            item_quantity = cart[product.slug]
            item_price = item_quantity * product.price
            subtotal = subtotal + item_price
            data.setdefault('items', []).append({
                'product': product,
                'quantity': item_quantity,
                'price': item_price,
            })
        data['subtotal'] = subtotal
        return data


def add_to_cart(request, slug):
    cart = request.session.setdefault('cart', {})
    cart[slug] = cart.get(slug, 0) + int(request.POST.get('quantity', 1))
    request.session['cart'] = cart
    return HttpResponseRedirect(reverse('shop:cart'))


def remove_from_cart(request, slug):
    cart = request.session.setdefault('cart', {})
    cart.pop(slug)
    request.session['cart'] = cart
    return HttpResponseRedirect(reverse('shop:cart'))


def empty_cart(request):
    del request.session['cart']
    return HttpResponseRedirect(reverse('shop:cart'))

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'shop/styles/base.css' %}">
        {% block metadata %}{% endblock %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <header>
            <search>
            <form action="{% url 'shop:product-list' %}" method="get">
                <input
                        name="search"
                        value="{{ request.GET.search }}"
                        type="search"
                        placeholder="Search">
                <button type="submit">Search</button>
            </form>
            </search>
            <p>
            <a href="{% url 'shop:cart' %}">Shopping cart</a>
            </p>
        </header>
        {% block content %}{% endblock %}
    </body>
</html>

shop/templates/shop/cart.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}Shopping Cart | E-Commerce Example{% endblock %}

{% block content %}
<h1>Shopping Cart</h1>
{% if items %}
<ol>
    {% for item in items %}
    <li>
        <section>
            <a href="{% url 'shop:product-detail' item.product.slug %}">
                <h2>{{ item.product.name }}</h2>
                <img
                        src="{% static item.product.get_image_path %}"
                        width="300"
                        height="200">
            </a>
            <p>Quantity: {{ item.quantity }}</p>
            <p>Price: ${{ item.price }}</p>
            <form
                    action="{% url 'shop:remove-from-cart' item.product.slug %}"
                    method="post">
                {% csrf_token %}
                <button>Remove from cart</button>
            </form>
        </section>
    </li>
    {% endfor %}
</ol>
<p>Subtotal: ${{ subtotal }}</p>
<form action="{% url 'shop:empty-cart' %}" method="post">
    {% csrf_token %}
    <button>Empty cart</button>
</form>
{% else %}
<p>Your shopping cart is empty.</p>
{% endif %}
{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}{{ product.name }} | E-Commerce Example{% endblock %}

{% block content %}
<h1>{{ product.name }}</h1>
<img
        src="{% static product.get_image_path %}"
        width="600"
        height="400"
        alt="{{ product.name }}">
<p>Price: ${{ product.price }}</p>
{% if product.description %}
<h2>Description</h2>
<p>{{ product.description }}</p>
{% endif %}
<h2>Categories</h2>
<ul>
    {% for category in product.categories.all %}
    <li>
        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
    </li>
    {% endfor %}
</ul>
<form action="{% url 'shop:add-to-cart' product.slug %}" method="post">
    {% csrf_token %}
    <p>
        <label for="quantity" id="quantity">Quantity:</label>
        <input id="quantity" name="quantity" value="1" min="1" type="number">
    </p>
    <button>Add to cart</button>
</form>
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'shop/base.html' %}

{% load static %}

{% load url_for_page %}

{% block title %}Search | E-Commerce Example{% endblock %}

{% block metadata %}
<link rel="stylesheet" href="{% static 'shop/styles/product_list.css' %}">
{% endblock %}

{% block content %}
<div class="product-list-main-container">
    <section class="product-list-sidebar">
        <h2>Categories</h2>
        <ul>
            <li>
                <a
                        {% if category_slug is not None %}
                        href="/products/"
                        {% endif %}>All</a>
                <span>({{ product_count }})</span>
            </li>
            {% for category in categories %}
            <li>
                <a
                        {% if category.slug != category_slug %}
                        href="{{ category.get_absolute_url }}"
                        {% endif %}>{{ category.name }}</a>
                <span>({{ category.product_set.count }})</span>
            </li>
            {% endfor %}
        </ul>
    </section>
    <main class="product-list-main">
        <h1>Search</h1>
        {% if product_list %}
        <p>Showing items {{ page_obj.start_index }}–{{ page_obj.end_index }} of {{ page_obj.paginator.count }}</p>
        <ol class="product-list">
            {% for product in product_list %}
            <li class="product-container">
                <article class="product">
                    <a
                            class="product-link"
                            href="{{ product.get_absolute_url }}"
                            aria-labelledby="{{ product.slug }}">
                        <hgroup class="product-link-heading">
                            <h2
                                    class="product-name"
                                    id="{{ product.slug }}">{{ product.name }}</h2>
                            <p class="product-price">${{ product.price }}</p>
                        </hgroup>
                        <img
                                class="product-image"
                                src="{% static product.get_image_path %}"
                                width="300"
                                height="200"
                                alt="{{ product.name }}">
                    </a>
                </article>
            </li>
            {% endfor %}
        </ol>
        <p>
        {% if page_obj.has_previous %}
        <a href="{% url_for_page 1 %}">First</a>
        <a href="{% url_for_page page_obj.previous_page_number %}">Previous</a>
        {% endif %}
        Page {{ page_obj.number }} of {{ paginator.num_pages }}
        {% if page_obj.has_next %}
        <a href="{% url_for_page page_obj.next_page_number %}">Next</a>
        <a href="{% url_for_page paginator.num_pages %}">Last</a>
        {% endif %}
        </p>
        {% else %}
        <p>No products matching the specified criteria were found.</p>
        {% endif %}
    </main>
</div>
{% endblock %}